### ISSUE TITLE
Build error while importing cursor

### ISSUE THREAD

**Issue by alvinhtml** [immutable-js/immutable-js#1795] opened 2020-10-23 10:02 UTC
immutable@4.0.0-rc.12

```js
import Cursor from 'immutable/contrib/cursor';
```

webpack@5.2.0 

```bash
ERROR in ./node_modules/immutable/contrib/cursor/index.js 25:0
Module parse failed: Unexpected token (25:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   '\n' +
|   'https://github.com/redbadger/immutable-cursor\n' +
> );
|
| /**
```

```js
typeof console === 'object' && console.warn && console.warn(
  'The Cursor API is deprecated and will be removed in a future major release.\n' +
  '\n' +
  'It is strongly suggested that you use the excellent `immutable-cursor` module\n' +
  'which has an extremely similar API but is much higher quality.\n' +
  '\n' +
  'https://github.com/redbadger/immutable-cursor\n' +
);
```

Why is there a trailing plus sign？

**Comment by Methuselah96** [comment] 2020-10-23 15:18
I don't know, but it's going to be removed in the next release, so I would suggest using `immutable-cursor` (or sticking with v3).

**Comment by Methuselah96** [comment] 2021-06-18 19:11
Duplicate of https://github.com/immutable-js/immutable-js/issues/1733.

**Closed by Methuselah96** 2021-06-18 19:11 UTC
