### ISSUE TITLE
Using Map with Typescript

### ISSUE THREAD

**Issue by Gerasimov94** [immutable-js/immutable-js#1706] opened 2019-04-26 14:26 UTC
Hello, i found an interesting issue. When i am passing an object in Map it works fine:
```js
import {Map} from 'immutable';
...
const myMap = Map({a: 1});
```
But when i am trying to pass an array like on screen below, compiler complains:
```js
const myMap = Map([[ "key", "value" ]]);
```

I took a that variant from here: https://immutable-js.github.io/immutable-js/docs/#/Map/Map

`Argument of type 'string[][]' is not assignable to parameter of type '{ [key: string]: {}; }'.
  Index signature is missing in type 'string[][]'`

In my opinion, it works that way because we have an overloaded Map functions at definitions file, and typescript choosing second variant instead of first.

``` ts
  immutable-nonambient.d.ts: 761

  export function Map<K, V>(collection: Iterable<[K, V]>): Map<K, V>;
  export function Map<V>(obj: {[key: string]: V}): Map<string, V>;
```

ts version: 3.3.333333

**Comment by vamshi-tg** [comment] 2021-06-28 17:40
Facing same problem. Created this csb for reference https://codesandbox.io/s/immutable-map-typescript-issue-56t35

**Comment by vamshi-tg** [comment] 2021-06-28 18:07
We can resolve the typescript error with the below steps.
```
const strTupleArr: [string, string][] = [["key", "value"]]
const myMap = Map(strTupleArr);
```

**Comment by jdeniau** [comment] 2021-06-29 10:14
Thank you for your bug report. The immutable-js oss fork will soon be merged and a fix for this issue has been included in #1833. Once this PR is merged, this issue will be resolved in the main branch. We will then do our best to to release the `4.0.0` version.

**Comment by jdeniau** [comment] 2021-07-08 21:27
Hi!
The 4.0.0-rc.14 version has been released and should fix this issue.
Feel free to test it and re-open this issue if the issue is still present.
Thank you!

**Closed by jdeniau** 2021-07-08 21:27 UTC
Labels: fixed-with-oss-merge, typescript

**Comment by ClusterH** [comment] 2021-11-24 16:19
faced same error even though tried use 4.0.0-rc.14

**Comment by jdeniau** [comment] 2021-11-30 08:55
@ClusterH can you try with the stable 4.0.0 and post a reproducible code snippet if there is the error is still present?
